sudo: required
dist: trusty

language: c

matrix:
  include:
    - os: osx

node_js:
  - 6

cache:
  directories:
    - node_modules

install:
  - nvm install 6
  - npm install -g yarn
  - yarn install

script:
  - npm run dist
